name: Dyninst OSes
description: 'Operating systems Dyninst is tested on'
outputs:
  matrix: ${{ jobs.make_oses.outputs.matrix }}

jobs:
  make_oses:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ fromJson(steps.values.outputs.names) }}
    steps:
      - id: values
        run: |
          # As yaml strings
          names+="'ubuntu-20.04, '"
          names+="'ubuntu-22.04, '"
          names+="'ubuntu-23.04, '"
          names+="'ubuntu-23.10, '"
          names+="'ubuntu-24.04, '"
          names+="'fedora-37, '"
          names+="'fedora-38, '"
          names+="'fedora-39, '"

          echo "names=[${names}]" >> $GITHUB_OUTPUT
