name: Dyninst OSes
description: 'Operating systems Dyninst is tested on'
outputs:
  matrix:
    - ubuntu-20.04
    - ubuntu-22.04
    - ubuntu-23.04
    - ubuntu-23.10
    - ubuntu-24.04
    - fedora-37
    - fedora-38
    - fedora-39
