name: Build Dyninst

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      os:
        required: true
        type: string
      extra-libs:
        required: false
        type: string
      extra-cmake-flags:
        required: false
        type: string
      c-compiler:
        required: true
        type: string
      cxx-compiler:
        required: true
        type: string
      is-clang:
        required: false
        type: boolean
        default: false
      build-type:
        required: false
        type: string
        default: 'ALL'

jobs:
  set_build_types:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.build_types }}
    steps:
    - id: set-matrix
      run: |
        type="${{ inputs.build-type }}"
        if test "$types" = "ALL"; then
          type="'DEBUG', 'RELWITHDEBINFO', 'RELEASE'"
        elif [[ ! "$types" =~ "," ]]; then
          # Add JSON quote
          #   Assume a comma-separated list is correctly quoted
          type="'${types}'"
        fi
        echo "build_types=[$type]" >> $GITHUB_OUTPUT

  build:
    needs: set_build_types
    strategy:
      fail-fast: false
      matrix:
         build-type: ${{ fromJson(needs.set_build_types.outputs.matrix) }}
    runs-on: ubuntu-latest
    name: ${{ inputs.name }} (${{ matrix.build-type }})
    steps:
      - run: echo "${{ matrix.build-type }}"
