# 1. Build with multiple versions of gcc and clang using the ubuntu-provided compiler
# 2. Using the latest version of each compiler, build against all supported C++ standards

name: Compiler multibuild

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  gcc-ubuntu-20_04:
    strategy:
      fail-fast: false
    uses: ./.github/workflows/build.yaml
    with:
      name: gcc-${{ matrix.version }}
      os: "ubuntu-20.04"
      c-compiler: "gcc-${{ matrix.version }}"
      cxx-compiler: "g++-${{ matrix.version }}"

  gcc-ubuntu-20_04:
    strategy:
      fail-fast: false
    uses: ./.github/workflows/build.yaml
    with:
      name: gcc-${{ matrix.version }}
      os: "ubuntu-20.04"
      c-compiler: "gcc-${{ matrix.version }}"
      cxx-compiler: "g++-${{ matrix.version }}"
      build-type: 'MOO'
