# 1. Build with multiple versions of gcc and clang using the ubuntu-provided compiler
# 2. Using the latest version of each compiler, build against all supported C++ standards

name: Compiler multibuild

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  use-oses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get OSes
        id: fetch-os
        uses: ./.github/actions/operating_systems
      - name: Use OSes
        run: echo ${{ steps.fetch-os.outputs.matrix }}
