# 1. Build with multiple versions of gcc and clang using the ubuntu-provided compiler
# 2. Using the latest version of each compiler, build against all supported C++ standards

name: Compiler multibuild

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(steps.fetch-os.outputs.names) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get OSes
        id: fetch-os
        uses: ./.github/actions/os-versions
      - name: ${{ matrix.os }}
        run: echo Hello from ${{ matrix.os }}
