# 1. Build with multiple versions of gcc and clang using the ubuntu-provided compiler
# 2. Using the latest version of each compiler, build against all supported C++ standards

name: Compiler multibuild

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  fetch-oses:
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.fetch-os.outputs.names }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get OSes
        id: fetch-os
        uses: ./.github/actions/os-versions
  
  use-oses:
    needs: fetch-oses
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.fetch-oses.outputs.names) }}
    steps:
      - name: ${{ matrix.os }}
        run: echo Hello from ${{ matrix.os }}
