# 1. Build with multiple versions of gcc and clang using the ubuntu-provided compiler
# 2. Using the latest version of each compiler, build against all supported C++ standards

name: Compiler multibuild

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  fetch-oses:
    uses: ./.github/workflows/oses.yaml
    
  use-oses:
    needs: fetch-oses
    steps:
    - run: echo ${{ needs.fetch-oses.outputs.matrix }}
