name: MacOS Test

on:
  pull_request:
     types: [opened, synchronize, reopened, ready_for_review]
     branches:
        - master
  workflow_dispatch:

jobs:

  mac-test:
    runs-on: macos-latest
    steps:
      - run: |
          #system_profiler SPHardwareDataType
          #system_profiler SPSoftwareDataType
          #clang++ --version
          otool -L $(which clang++)
