name: Pull Request Tests

on:
  pull_request:
     branches:
        - master
     paths:
       - 'common/**'
       - 'dataflowAPI/**'
       - 'dwarf/**'
       - 'dynC_API/**'
       - 'dyninstAPI/**'
       - 'dyninstAPI_RT/**'
       - 'elf/**'
       - 'external/**'
       - 'instructionAPI/**'
       - 'parseAPI/**'
       - 'parseThat/**'
       - 'patchAPI/**'
       - 'proccontrol/**'
       - 'stackwalk/**'
       - 'symlite/**'
       - 'symtabAPI/**'
     types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:

  get-oses:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.all.outputs.all }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: all
        uses: ./.github/actions/os-versions

  pr-tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    needs: get-oses
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.get-oses.outputs.all) }}
        c-compiler: ['gcc', 'clang']
        include:
          - c-compiler: 'gcc'
            cxx-compiler: 'g++'
          - c-compiler: 'clang'
            cxx-compiler: 'clang++'
    permissions:
      packages: read
    container:
      image: ghcr.io/dyninst/amd64/${{ matrix.os }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    name: PR tests ${{ matrix.c-compiler }} on ${{ matrix.os }}
    steps:
      - name: Checkout Dyninst
        uses: actions/checkout@v4
        with:
          path: "src"  # relative to ${GITHUB_WORKSPACE}

      - name: Build Dyninst
        uses: ./src/.github/actions/build
        with:
          os: ${{ matrix.os }}
          c-compiler: ${{ matrix.c-compiler }}
          cxx-compiler: ${{ matrix.cxx-compiler }}
          src-dir: "${GITHUB_WORKSPACE}/src"
          install-dir: "${GITHUB_WORKSPACE}/install"

      - name: Checkout Test Suite
        if: ${{ matrix.c-compiler != 'clang' }}
        uses: actions/checkout@v4
        with:
          repository: dyninst/testsuite
          path: "testsuite"  # relative to ${GITHUB_WORKSPACE}

      - name: Build testsuite
        if: ${{ matrix.c-compiler != 'clang' }}
        shell: bash
        run: |
          set -ex
          cd ${GITHUB_WORKSPACE}/testsuite; mkdir build; cd build
          cmake .. -DDyninst_ROOT=${GITHUB_WORKSPACE}/install
          cmake --build . --parallel 2

      - name: Checkout Examples
        uses: actions/checkout@v4
        with:
          repository: dyninst/examples
          path: "examples"  # relative to ${GITHUB_WORKSPACE}

      - name: Build examples
        shell: bash
        run: |
          set -ex
          cd ${GITHUB_WORKSPACE}/examples; mkdir build; cd build
          cmake .. -DDyninst_ROOT=${GITHUB_WORKSPACE}/install
          cmake --build . --parallel 2

      - name: Checkout External Tests
        uses: actions/checkout@v4
        with:
          repository: dyninst/external-tests
          path: "external-tests"  # relative to ${GITHUB_WORKSPACE}

      - name: Build external tests
        shell: bash
        run: |
          set -ex
          cd ${GITHUB_WORKSPACE}/external-tests; mkdir build; cd build
          cmake .. -DDyninst_ROOT=${GITHUB_WORKSPACE}/install
          cmake --build . --parallel 2

      - name: Run external tests
        shell: bash
        run: |
          set -ex
          cd ${GITHUB_WORKSPACE}/external-tests/build
          ctest -VV --output-on-failure .
